name: Backfill Map

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pull the latest release
        run: |
          gh release download --repo ProjectTSB/TheSkyBlessing --pattern "TheSkyBlessing.zip" --dir ./download

      - name: Run backfill app
        run: |
          python backfill.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "TheSkyBlessing_CN.zip"
          path: "./TheSkyBlessing_CN.zip"
